# Generated by Django 2.0.7 on 2018-08-12 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_workout_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
