# Generated by Django 2.0.7 on 2018-08-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_pushedworkout_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushedworkout',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pushedworkout',
            name='inclass',
            field=models.BooleanField(default=True),
        ),
    ]
