# Generated by Django 2.0.7 on 2018-08-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20180813_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushedworkout',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pushedworkout',
            name='inclass',
            field=models.BooleanField(default=True),
        ),
    ]
