# Generated by Django 2.0.7 on 2018-08-13 04:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20180813_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushedworkout',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 13, 4, 8, 52, 927768, tzinfo=utc)),
        ),
    ]
