# Generated by Django 2.0.7 on 2018-08-13 04:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_pushedworkout_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushedworkout',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 13, 4, 9, 35, 692722, tzinfo=utc)),
        ),
    ]
