# Generated by Django 2.0.7 on 2018-08-13 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20180813_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushedworkout',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
